/* ============================================================
   TRUMP service worker.

   Goal: the app shell loads instantly and, with no network at all, you
   still get a playable game — offline navigations fall back to
   /solo.html, the self-contained single-player build.

   Never cached: /ws (WebSocket), /health, /stats — those must always
   hit the network or fail honestly.
   ============================================================ */
// GENERATED by scripts/build-assets.js — a hash of the shell below, so a deploy
// that changes any of these files evicts the old cache. Do not edit by hand.
const VERSION = "trump-e9695115d5a4";
const SHELL = [
  "/", "/index.html", "/solo.html", "/manifest.webmanifest",
  "/icon-192.png", "/icon-512.png", "/icon-maskable-512.png", "/apple-touch-icon.png", "/favicon-32.png",
  "/js/util/dom.js", "/js/util/prefs.js", "/js/cards/labels.js", "/js/cards/icons.js", "/js/cards/deck.js",
];
const NEVER = ["/ws", "/health", "/stats"];

self.addEventListener("install", (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(VERSION);
    // individual puts: one 404 shouldn't fail the whole install like addAll does
    await Promise.all(SHELL.map(async (url) => {
      try { const res = await fetch(url, { cache: "reload" }); if (res.ok) await cache.put(url, res); } catch {}
    }));
    self.skipWaiting();
  })());
});

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k !== VERSION) await caches.delete(k);
    await self.clients.claim();
  })());
});

self.addEventListener("message", (e) => { if (e.data === "skipWaiting") self.skipWaiting(); });

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (NEVER.some(p => url.pathname === p || url.pathname.startsWith(p + "/"))) return;

  // Navigations: fresh when online, cached shell when not, solo game as the last resort.
  if (req.mode === "navigate") {
    e.respondWith((async () => {
      try {
        const res = await fetch(req);
        if (res.ok) (await caches.open(VERSION)).put("/index.html", res.clone());
        return res;
      } catch {
        return (await caches.match(req)) || (await caches.match("/index.html")) ||
               (await caches.match("/solo.html")) || new Response("offline", { status: 503 });
      }
    })());
    return;
  }

  // Static assets: serve from cache, refresh in the background.
  e.respondWith((async () => {
    const hit = await caches.match(req);
    const net = fetch(req).then(async (res) => {
      if (res.ok) (await caches.open(VERSION)).put(req, res.clone());
      return res;
    }).catch(() => hit);
    return hit || net;
  })());
});
