/* ============================================================
   TRUMP service worker.

   Goal: the app shell loads instantly and, with no network at all, it is
   still there: /index.html is always in the precache and is refreshed on
   every successful online navigation, so it answers any offline navigation
   that isn't itself an exact cache hit. /solo.html is precached too and
   works offline when navigated to directly (a link, a bookmark, the
   manifest shortcut) — but it is not the generic offline fallback; that
   role belongs to the app shell, since /index.html can't be missing from
   the cache in normal operation.

   Never cached: /ws (WebSocket), /health, /stats — those must always
   hit the network or fail honestly.
   ============================================================ */
// GENERATED by scripts/build-assets.js — a hash of the shell below, so a deploy
// that changes any of these files evicts the old cache. Do not edit by hand.
const VERSION = "trump-e4686be02bd9";
const SHELL = [
  "/", "/apple-touch-icon.png", "/css/base.css", "/css/panels.css", "/css/responsive.css", "/css/table.css", "/css/tokens.css", "/favicon-32.png", "/icon-192.png", "/icon-512.png", "/icon-maskable-512.png", "/index.html", "/js/cards/deck.js", "/js/cards/icons.js", "/js/cards/labels.js", "/js/core/engine/ai/heuristic.js", "/js/core/engine/ai/index.js", "/js/core/engine/ai/pimc.js", "/js/core/engine/bidding.js", "/js/core/engine/cards.js", "/js/core/engine/constants.js", "/js/core/engine/contract.js", "/js/core/engine/flow.js", "/js/core/engine/index.js", "/js/core/engine/log.js", "/js/core/engine/match.js", "/js/core/engine/play.js", "/js/core/engine/random.js", "/js/core/engine/scoring.js", "/js/main.js", "/js/net.js", "/js/pwa.js", "/js/screens/game.js", "/js/screens/join.js", "/js/screens/lobby.js", "/js/session.js", "/js/share.js", "/js/solo.js", "/js/ui/actionbar.js", "/js/ui/ambient.js", "/js/ui/chat.js", "/js/ui/hand.js", "/js/ui/layout.js", "/js/ui/log.js", "/js/ui/modals.js", "/js/ui/rails.js", "/js/ui/sound.js", "/js/ui/table.js", "/js/util/dom.js", "/js/util/prefs.js", "/manifest.webmanifest", "/solo.html",
];
const NEVER = ["/ws", "/health", "/stats"];

self.addEventListener("install", (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(VERSION);
    // individual puts: one 404 shouldn't fail the whole install like addAll does
    await Promise.all(SHELL.map(async (url) => {
      try { const res = await fetch(url, { cache: "reload" }); if (res.ok) await cache.put(url, res); } catch {}
    }));
    self.skipWaiting();
  })());
});

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k !== VERSION) await caches.delete(k);
    await self.clients.claim();
  })());
});

self.addEventListener("message", (e) => { if (e.data === "skipWaiting") self.skipWaiting(); });

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (NEVER.some(p => url.pathname === p || url.pathname.startsWith(p + "/"))) return;

  // Navigations: fresh when online, cached shell when not, solo game as the last resort.
  if (req.mode === "navigate") {
    e.respondWith((async () => {
      try {
        const res = await fetch(req);
        if (res.ok) (await caches.open(VERSION)).put("/index.html", res.clone());
        return res;
      } catch {
        return (await caches.match(req)) || (await caches.match("/index.html")) ||
               (await caches.match("/solo.html")) || new Response("offline", { status: 503 });
      }
    })());
    return;
  }

  // Static assets: serve from cache, refresh in the background.
  e.respondWith((async () => {
    const hit = await caches.match(req);
    const net = fetch(req).then(async (res) => {
      if (res.ok) (await caches.open(VERSION)).put(req, res.clone());
      return res;
    }).catch(() => hit);
    return hit || net;
  })());
});
